version: "3.8"

services:
  mariadb:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=verysecret
      - MARIADB_ROOT_HOST=%
      - MARIADB_DATABASE=crm_chatbot
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mariadb
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: verysecret

volumes:
  mariadb_data:
